shared: &shared
  - ".github/**"
  - "build-scripts/**"
docker:
  - *shared
  - ".dockerignore"
  - Dockerfile
rust:
  - *shared
  - ".cargo/**"
  - "**/*.toml"
  - "src/**"
  - "tests/**"
  - Cargo.lock
