shared: &shared
  - ".github/**"
  - "build-scripts/**"
docker:
  - *shared
  - ".dockerignore"
  - Dockerfile
rust: &rust
  - *shared
  - ".cargo/**"
  - "**/*.toml"
  - "src/**"
  - "tests/**"
  - Cargo.lock
# the package installs both files, see `license-file` and `assets` in `[package.metadata.deb]`
deb:
  - *rust
  - LICENSE
  - README.md
