version: "2"                                                  

exclude_patterns:                                             
  - "*"                                                       
  - "*.*"                                                     
  - ".*"                                                      
  - ".*/**"                                                   
  - "**"                                                      
  - "!src/**"
  - "!tests/**"
