---
overrides:
  - files:
      - "**/*.{yml,yaml}"
    options:
      singleQuote: false
  - files:
      - "**/*.json"
    options:
      tabWidth: 4
      trailingComma: none
  - files:
      - "package.json"
      - "package-lock.json"
    options:
      tabWidth: 2
