absolute-paths-allowed-crates = ["std"]
disallowed-macros = [
    { path = "std::assert_ne", reason = "use `pretty_assertions::assert_ne` instead" },
    { path = "std::assert_eq", reason = "use `pretty_assertions::assert_eq` instead" },
    { path = "std::assert_matches", reason = "use `pretty_assertions::assert_matches` instead" },
    { path = "std::dbg", reason = "use ::tracing::event!(::tracing::Level::DEBUG, ...) instead, dbg! bypasses the log pipeline" },
    { path = "tracing::trace", reason = "use ::tracing::event!(::tracing::Level::TRACE, ...) instead" },
    { path = "tracing::debug", reason = "use ::tracing::event!(::tracing::Level::DEBUG, ...) instead" },
    { path = "tracing::info", reason = "use ::tracing::event!(::tracing::Level::INFO, ...) instead" },
    { path = "tracing::warn", reason = "use ::tracing::event!(::tracing::Level::WARN, ...) instead" },
    { path = "tracing::error", reason = "use ::tracing::event!(::tracing::Level::ERROR, ...) instead" },
    { path = "tracing::trace_span", reason = "use ::tracing::span!(::tracing::Level::TRACE, ...) instead" },
    { path = "tracing::debug_span", reason = "use ::tracing::span!(::tracing::Level::DEBUG, ...) instead" },
    { path = "tracing::info_span", reason = "use ::tracing::span!(::tracing::Level::INFO, ...) instead" },
    { path = "tracing::warn_span", reason = "use ::tracing::span!(::tracing::Level::WARN, ...) instead" },
    { path = "tracing::error_span", reason = "use ::tracing::span!(::tracing::Level::ERROR, ...) instead" },
]
disallowed-methods = [
    # https://github.com/serde-rs/json/issues/160
    "serde_json::from_reader",
]
disallowed-names = ["bar", "baz", "e", "err", "foo", "ok", "quux"]
disallowed-types = [
    { path = "std::collections::HashMap", replacement = "hashbrown::HashMap", reason = "The standard library version sacrifices performance for HashDos resistance, which should be chosen explicitly" },
    { path = "std::collections::HashSet", replacement = "hashbrown::HashSet", reason = "The standard library version sacrifices performance for HashDos resistance, which should be chosen explicitly" },
]
enforced-import-renames = [
    { path = "serde_json::from_slice", rename = "from_json_slice" },
    { path = "serde_json::from_str", rename = "from_json_str" },
    { path = "serde_json::from_value", rename = "from_json_value" },
    { path = "serde_json::to_value", rename = "to_json_value" },
    { path = "serde_json::value::to_raw_value", rename = "to_raw_json_value" },
    { path = "serde_json::value::RawValue", rename = "RawJsonValue" },
    { path = "serde_json::Value", rename = "JsonValue" },
]
standard-macro-braces = [
    { name = "quote", brace = "{" },
    { name = "quote::quote", brace = "{" },
]
warn-on-all-wildcard-imports = true
