FROM mcr.microsoft.com/devcontainers/rust:2-1-bullseye@sha256:3946a1aaef7a28a8b9a00ca5302bc4a78bf253e395a8072e46ab0936d6dd62bf

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
