FROM mcr.microsoft.com/devcontainers/rust:2-1-bullseye@sha256:c880d7816ecacb81f28cf1778375cca48dd5f6d07d6a761e023def902a1dc1d4

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
