#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

cargo test --workspace --all-targets --all-features
cargo clippy --workspace --all-targets --all-features -- --deny warnings
cargo fmt --all -- --check
