#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

cargo test --workspace --all-targets --all-features
cargo clippy --workspace --all-targets --all-features -- --deny clippy::all --warn clippy::pedantic --warn clippy::cargo
cargo fmt --all -- --check --verbose
