# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Compare release image

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  repo-has-container:
    name: Repo has container?
    runs-on: ubuntu-slim
    if: startsWith(github.head_ref, 'release/v')
    outputs:
      has_container: ${{ steps.determine.outputs.has_container }}
    steps:
      - name: Repo has docker container?
        shell: bash
        id: determine
        run: |
          has_container="${{ vars.HAS_CONTAINER }}"
          echo "has_container=${has_container:-false}" >> "${GITHUB_OUTPUT}"

  compare:
    name: Compare release image against latest
    runs-on: ubuntu-latest
    needs:
      - repo-has-container
    if: fromJSON(needs.repo-has-container.outputs.has_container) == true
    steps:
      - name: Set full image name
        shell: bash
        run: |
          echo "FULL_IMAGE_NAME=${REGISTRY,,}/${IMAGE_NAME,,}" >> "${GITHUB_ENV}"

      - name: Set up Docker
        uses: docker/setup-docker-action@77e84dbf09b47d1e29270283c22f16145aa85ca1 # v5.4.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Scout Compare (linux/amd64)
        uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
        with:
          command: compare
          image: "${{ env.FULL_IMAGE_NAME }}:edge"
          platform: linux/amd64
          to: "${{ env.FULL_IMAGE_NAME }}:latest"
          dockerhub-user: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          organization: ${{ vars.DOCKERHUB_USERNAME }}

      - name: Docker Scout Compare (linux/arm64)
        uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
        with:
          command: compare
          image: "${{ env.FULL_IMAGE_NAME }}:edge"
          platform: linux/arm64
          to: "${{ env.FULL_IMAGE_NAME }}:latest"
          dockerhub-user: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          organization: ${{ vars.DOCKERHUB_USERNAME }}
