# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint commits

on:
  pull_request:
    branches:
      - main

concurrency:
  # each new commit to a PR runs this workflow
  # so we need to avoid a long running older one from overwriting the 'pr-<number>-latest'
  group: "${{ github.workflow }} @ ${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false
          fetch-depth: 0

      - name: Install cocogitto to lint commits
        uses: taiki-e/install-action@7572810d7dd469b651bb7793945692cf78da5dd7 # v2.85.0
        with:
          tool: cocogitto

      - name: Check the commits
        shell: bash
        run: |
          cog check --ignore-merge-commits
