# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint commits

on:
  pull_request:
    branches:
      - main

concurrency:
  # each new commit to a PR runs this workflow
  # so we need to avoid a long running older one from overwriting the 'pr-<number>-latest'
  group: "${{ github.workflow }} @ ${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false
          fetch-depth: 0

      - name: Install cocogitto to lint commits
<<<<<<< HEAD
        uses: taiki-e/install-action@6c1f7cf125e42770ff087ea443901b487cc5471a # v2.79.5
||||||| 1cd12422
        uses: taiki-e/install-action@65851e10cd6c377f11a60e600abc07cb08643468 # v2.79.3
=======
        uses: taiki-e/install-action@f48d2f8ba2b452934c948b7be1a768079c3632ff # v2.79.6
>>>>>>> upstream/main
        with:
          tool: cocogitto

      - name: Check the commits
        shell: bash
        run: |
          cog check --ignore-merge-commits
