# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Machete

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  machete:
    name: Machete
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Set up toolchain
        shell: bash
        run: |
          rm ${HOME}/.cargo/bin/cargo-fmt
          rm ${HOME}/.cargo/bin/rust-analyzer
          rm ${HOME}/.cargo/bin/rustfmt

          rustup self update
          rustup update
          rustup show active-toolchain || rustup toolchain install
          rustup show

          cargo --version

      - name: Install cargo-machete to ensure we don't have unneeded packages
        uses: taiki-e/install-action@682e7d9e49c5e653d371fc6adbda67653461378a # v2.82.4
        with:
          tool: cargo-machete

      - name: Run cargo machete
        shell: bash
        run: |
          cargo machete
