# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Machete

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  machete:
    name: Machete
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - name: Set up toolchain
        shell: bash
        run: |
          rm ${HOME}/.cargo/bin/cargo-fmt
          rm ${HOME}/.cargo/bin/rust-analyzer
          rm ${HOME}/.cargo/bin/rustfmt

          rustup self update
          rustup update
          rustup show active-toolchain || rustup toolchain install
          rustup show

          cargo --version

      - name: Install cargo-machete to ensure we don't have unneeded packages
        uses: taiki-e/install-action@0c7a94999971db56e9df89df226240aab222e776 # v2.75.14
        with:
          tool: cargo-machete

      - name: Run cargo machete
        shell: bash
        run: |
          cargo machete
