# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Retag container after release

on:
  release:
    types:
      - released
      - prereleased

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false # last one must win in case of multiple releases

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_IMAGE_NAME: ${{ vars.DOCKERHUB_IMAGE_NAME }}

jobs:
  repo-has-container:
    name: Repo has container?
    runs-on: ubuntu-latest
    outputs:
      has_container: ${{ steps.determine.outputs.has_container }}

    steps:
      - name: Repo has docker container?
        id: determine
        shell: bash
        run: |
          has_container="${{ vars.HAS_CONTAINER }}"
          echo "has_container=${has_container:-false}" >> "${GITHUB_OUTPUT}"

  retag-containers:
    name: Retag the containers
    runs-on: ubuntu-latest
    needs:
      - repo-has-container
    if: |
      fromJSON(needs.repo-has-container.outputs.has_container) == true
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5.0.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}

      - name: Log into Docker Hub
        if: env.DOCKERHUB_IMAGE_NAME != ''
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set full image name
        shell: bash
        run: |
          echo "FULL_IMAGE_NAME=${REGISTRY,,}/${IMAGE_NAME,,}" >> "${GITHUB_ENV}"
          echo "FULL_DOCKERHUB_IMAGE_NAME=docker.io/${DOCKERHUB_IMAGE_NAME,,}" >> "${GITHUB_ENV}"

      - name: Find source tag using GitHub CLI
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo="${{ github.repository }}"
          repo_lower="${repo,,}"

          OLD_TAG=$(gh api /users/${{ github.repository_owner }}/packages/container/${repo_lower##*/}/versions \
            --paginate \
            --jq '.[] | .metadata.container.tags[]' | grep "^sha-${{ github.sha }}-.*\$" | head --lines 1) # .* is actual or retag

          if [ -z "${OLD_TAG}" ]; then
            echo "::error::No matching source tag found for SHA ${{ github.sha }}"
            exit 1
          fi

          echo "OLD_TAG=${OLD_TAG}" >> "${GITHUB_ENV}"

      - name: Set the new TAGs
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }}
            type=semver,pattern={{version}},prefix=v

      - name: Set the new Docker Hub TAGs
        if: env.DOCKERHUB_IMAGE_NAME != ''
        id: meta-dockerhub
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: "docker.io/${{ env.DOCKERHUB_IMAGE_NAME }}"
          tags: |
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }}
            type=semver,pattern={{version}},prefix=v

      - name: Actually re-tag the container
        shell: bash
        run: |
          echo "${{ steps.meta.outputs.tags }}" | while IFS= read -r new_tag
            do
              docker buildx imagetools create --tag "${new_tag}" "${FULL_IMAGE_NAME}:${OLD_TAG}"
          done

      - name: Copy the container to Docker Hub
        if: env.DOCKERHUB_IMAGE_NAME != ''
        shell: bash
        run: |
          echo "${{ steps.meta-dockerhub.outputs.tags }}" | while IFS= read -r new_tag
            do
              docker buildx imagetools create --tag "${new_tag}" "${FULL_IMAGE_NAME}:${OLD_TAG}"
          done
